# Generated by Django 4.2.8 on 2023-12-08 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCrudo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='media/')),
                ('tipo', models.CharField(choices=[('aerogravimetria', 'Gravimetría aérea'), ('batimetria', 'Gravimetría oceánica'), ('nivelacion', 'Nivelación'), ('gravterrabs', 'Gravedad terrestre absoluta'), ('gravterrrel', 'Gravedad terrestre relativa')], max_length=20)),
                ('detalle', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivo_crudo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivo crudo',
                'verbose_name_plural': 'archivos crudos',
                'ordering': ('-id',),
            },
        ),
    ]
