# Generated by Django 4.2.8 on 2023-12-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivocrudo',
            name='archivo',
            field=models.FileField(upload_to='crudos/'),
        ),
    ]
