# Generated by Django 4.2.8 on 2023-12-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada_datos', '0002_alter_archivocrudo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivocrudo',
            name='archivo',
            field=models.FileField(upload_to='media/crudos/'),
        ),
    ]
