# Generated by Django 4.2.8 on 2023-12-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizar', '0002_alter_datoaereo_a_a_li'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoaereo',
            old_name='xi',
            new_name='zeta',
        ),
        migrations.RemoveField(
            model_name='gravimetriat',
            name='xi',
        ),
        migrations.RemoveField(
            model_name='nivelacion',
            name='xi',
        ),
        migrations.AddField(
            model_name='datoaereo',
            name='N',
            field=models.DecimalField(decimal_places=12, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=15),
        ),
        migrations.AddField(
            model_name='gravimetriat',
            name='zeta',
            field=models.DecimalField(decimal_places=12, default=-999.99999, help_text='Altura anómala según modelo geoidal global', max_digits=15),
        ),
        migrations.AddField(
            model_name='nivelacion',
            name='zeta',
            field=models.DecimalField(decimal_places=12, default=-999.99999, help_text='Altura anómala según modelo geoidal global', max_digits=15),
        ),
        migrations.AlterField(
            model_name='gravimetriat',
            name='N',
            field=models.DecimalField(decimal_places=12, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=15),
        ),
        migrations.AlterField(
            model_name='nivelacion',
            name='N',
            field=models.DecimalField(decimal_places=12, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=15),
        ),
    ]
