# Generated by Django 4.2.8 on 2023-12-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizar', '0005_alter_datoaereo_n_alter_datoaereo_zeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoaereo',
            name='N',
            field=models.DecimalField(decimal_places=4, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='a_a_li',
            field=models.DecimalField(decimal_places=3, help_text='Anomalía de aire libre', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='h_adj',
            field=models.DecimalField(decimal_places=3, help_text='altitud geométrica ajustada del avión (h)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='radar',
            field=models.DecimalField(decimal_places=4, help_text='Altimetría de radar', max_digits=10),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='zeta',
            field=models.DecimalField(decimal_places=4, default=-999.99999, help_text='Altura anómala según modelo geoidal global en la superficie', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gravimetriat',
            name='N',
            field=models.DecimalField(decimal_places=5, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=9),
        ),
        migrations.AlterField(
            model_name='gravimetriat',
            name='zeta',
            field=models.DecimalField(decimal_places=5, default=-999.99999, help_text='Altura anómala según modelo geoidal global en la superficie', max_digits=9),
        ),
    ]
