# Generated by Django 4.2.8 on 2023-12-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizar', '0006_alter_datoaereo_n_alter_datoaereo_a_a_li_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoaereo',
            name='N',
            field=models.DecimalField(decimal_places=3, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='a_a_li',
            field=models.DecimalField(decimal_places=3, help_text='Anomalía de aire libre', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='h_adj',
            field=models.DecimalField(decimal_places=3, help_text='altitud geométrica ajustada del avión (h)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='h_cru',
            field=models.DecimalField(decimal_places=3, help_text='altitud geométrica cruda del avión (h)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='radar',
            field=models.DecimalField(decimal_places=3, help_text='Altimetría de radar', max_digits=8),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='zeta',
            field=models.DecimalField(decimal_places=3, default=-999.99999, help_text='Altura anómala según modelo geoidal global en la superficie', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gravimetriat',
            name='N',
            field=models.DecimalField(decimal_places=3, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=8),
        ),
        migrations.AlterField(
            model_name='gravimetriat',
            name='h_t',
            field=models.DecimalField(decimal_places=3, help_text='Altura geométrica h del punto', max_digits=8),
        ),
        migrations.AlterField(
            model_name='gravimetriat',
            name='zeta',
            field=models.DecimalField(decimal_places=3, default=-999.99999, help_text='Altura anómala según modelo geoidal global en la superficie', max_digits=8),
        ),
        migrations.AlterField(
            model_name='nivelacion',
            name='N',
            field=models.DecimalField(decimal_places=3, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=8),
        ),
        migrations.AlterField(
            model_name='nivelacion',
            name='cota',
            field=models.DecimalField(decimal_places=3, help_text='Altura sobre el nivel del mar', max_digits=8),
        ),
        migrations.AlterField(
            model_name='nivelacion',
            name='h_t',
            field=models.DecimalField(decimal_places=3, help_text='Altura geométrica h del punto', max_digits=8),
        ),
        migrations.AlterField(
            model_name='nivelacion',
            name='zeta',
            field=models.DecimalField(decimal_places=3, default=-999.99999, help_text='Altura anómala según modelo geoidal global en la superficie', max_digits=8),
        ),
    ]
