# Generated by Django 4.2.8 on 2023-12-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estandarizar', '0007_alter_datoaereo_n_alter_datoaereo_a_a_li_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoaereo',
            name='N',
            field=models.DecimalField(decimal_places=5, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='datoaereo',
            name='zeta',
            field=models.DecimalField(decimal_places=5, default=-999.99999, help_text='Altura anómala según modelo geoidal global en la superficie', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gravimetriat',
            name='N',
            field=models.DecimalField(decimal_places=5, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=8),
        ),
        migrations.AlterField(
            model_name='gravimetriat',
            name='zeta',
            field=models.DecimalField(decimal_places=5, default=-999.99999, help_text='Altura anómala según modelo geoidal global en la superficie', max_digits=8),
        ),
        migrations.AlterField(
            model_name='nivelacion',
            name='N',
            field=models.DecimalField(decimal_places=5, default=-999.99999, help_text='Ondulación geoidal según modelo geoidal global', max_digits=8),
        ),
        migrations.AlterField(
            model_name='nivelacion',
            name='zeta',
            field=models.DecimalField(decimal_places=5, default=-999.99999, help_text='Altura anómala según modelo geoidal global en la superficie', max_digits=8),
        ),
    ]
